FROM postgres:17.1-alpine3.20
ENV POSTGRES_USER=${DB_USER} \
    POSTGRES_PASSWORD=${DB_PASSWORD} \
    POSTGRES_DB=${DB_NAME}

RUN mkdir -p /var/lib/postgresql/data && \
    chown -R postgres:postgres /var/lib/postgresql/data && \
    chmod 700 /var/lib/postgresql/data

USER postgres

EXPOSE 5432

CMD ["postgres"]